# Generated by Django 3.0.5 on 2022-03-30 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('diagnosisID', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('diagnosis', models.CharField(max_length=256)),
                ('test_recommendation', models.CharField(max_length=256)),
                ('prescription', models.CharField(max_length=256)),
                ('appointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Appointment')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('value', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=128)),
                ('height', models.DecimalField(decimal_places=2, max_digits=6)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('insuranceID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('paymentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('appointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Appointment')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('testID', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('result', models.CharField(max_length=255)),
                ('diagnosisID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Diagnosis')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient')),
                ('paymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Payment')),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='testID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Test'),
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient')),
                ('paymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Payment')),
            ],
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='doctorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor'),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnosisID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Diagnosis'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Doctor'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='paymentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Payment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='testID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Test'),
        ),
    ]
