# Generated by Django 3.0.5 on 2022-03-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220330_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='insuranceID',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
