# Generated by Django 4.0 on 2022-03-31 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220330_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='paymentID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.payment'),
        ),
    ]
