# Generated by Django 4.0 on 2022-04-01 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_merge_20220331_1924'),
        ('app', '0006_merge_20220401_1127'),
    ]

    operations = [
    ]
