# Generated by Django 4.0.3 on 2022-04-02 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_test_diagnosisid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='patientID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.patient'),
        ),
    ]
