# Generated by Django 3.0.5 on 2022-04-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_patient_age_alter_patient_gender_and_more'),
        ('app', '0015_auto_20220402_1906'),
    ]

    operations = [
    ]
