# Generated by Django 4.0.3 on 2022-04-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_merge_20220402_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='prescription',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
